### ISSUE TITLE
Issue with the new update ghostscript4js@2.0.5

### ISSUE THREAD

**Issue by dvoch** [Inist-CNRS/ghostscript-js#6]
Hi, I tried to run npm update today and when running the update of ghostscript4js I have this issue:

Error: Cannot find module 'C:\Tools\EB\back\node_modules\ghostscript4js\gs4js-env-dll.js'
...
gyp: Call to 'node gs4js-env-dll.js' returned exit status 1 while in binding.gyp. while trying to load binding.gyp

Anyone encountered this issue?
Thanks for any helps!
Regards
D.

**Comment by rmeja** [comment]
Sorry for not have the answer to your problem but perhaps you should post your issue here : https://github.com/NickNaso/ghostscript4js
