### ISSUE TITLE
NodeJS 12 Support

### ISSUE THREAD

**Issue by mmejia27** [Inist-CNRS/ghostscript-js#7]
When installing and building ghostscript-js, I get the following error on NodeJS v12.18.3:
```
ghostscript-js/src/ghostscript-node.cpp:87:85: error: no matching function for call to ‘v8::Value::ToString()’
   87 |             v8::String::Utf8Value val(Nan::Get(input, i).ToLocalChecked()->ToString());
```

**Comment by rmeja** [comment]
Hello, 
I fixed the error and normally it should work on NodeJS v12. Can you test on your own and confirm that everything is good?

**Comment by mmejia27** [comment]
Hello!

Thanks for the quick response. That seems to have resolved the issue.

Thanks again!
